apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: urbannes
  namespace: argocd

  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: git://git-server.argocd.svc.cluster.local/urbannes.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: urbannes
  syncPolicy:
    automated:

      prune: true

      selfHeal: true
    syncOptions:

      - CreateNamespace=true
  revisionHistoryLimit: 10
