services:
  auth-api:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/auth-api:${IMAGE_TAG:-latest}
    environment:
      CI: "true"

      RESEND_API_KEY: ""

  booking-api:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/booking-api:${IMAGE_TAG:-latest}

  booking-worker:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/booking-worker:${IMAGE_TAG:-latest}

  notification-service:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/notification-service:${IMAGE_TAG:-latest}
    environment:

      RESEND_API_KEY: ""

  analytics-api:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/analytics-api:${IMAGE_TAG:-latest}

  gateway-graphql:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/gateway-graphql:${IMAGE_TAG:-latest}

  gateway:
    image: ${REGISTRY}/${IMAGE_NAMESPACE}/gateway:${IMAGE_TAG:-latest}
