apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: notification-service-pdb
  namespace: urbannes
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: notification-service
