apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: urbannes

resources:
  - base/namespace.yaml
  - base/storageclass.yaml
  - base/configmap.yaml
  - base/secret.yaml
  - postgres/
  - redis-cache/
  - redis-coord/
  - kafka/
  - auth-api/
  - booking-api/
  - booking-worker/
  - analytics-api/
  - gateway-graphql/
  - notification-service/
  - gateway/

  - base/networkpolicies.yaml
