apiVersion: v1
kind: ConfigMap
metadata:
  name: urbannest-config
  namespace: urbannest
data:
  KAFKA_BROKERS: "kafka:9092"
  PGHOST: "postgres"
  PGPORT: "5432"
  PGDATABASE: "urbannest"
  REDIS_CACHE_HOST: "redis-cache"
  REDIS_CACHE_PORT: "6379"
  REDIS_LOCK_HOST: "redis-coord"
  REDIS_LOCK_PORT: "6379"
  REDIS_HOST: "redis-coord"
  REDIS_PORT: "6379"
  SEAT_LOCK_TTL_MS: "300000"
  REPLY_TIMEOUT_MS: "5000"
  PUBLIC_SHORT_URL_BASE: "http://localhost:8080/s"
  AUTH_API_GRAPHQL_URL: "http://auth-api:4600/graphql"
