apiVersion: v1
kind: Secret
metadata:
  name: urbannes-secrets
  namespace: urbannes
type: Opaque
data:
  PGUSER: dXJiYW5uZXM=
  PGPASSWORD: dXJiYW5uZXM=
  JWT_SECRET: dXJiYW5uZXMtZGV2LWp3dC1zZWNyZXQtY2hhbmdlLW1l
  GOOGLE_CLIENT_ID: MTAxMjUwMzk3NTg5NS02cDRscGd0cm5sYTQ1azB0amEzMnQwZnN0aGpkaW5nZy5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQ==
  RAZORPAY_KEY_ID: cnpwX3Rlc3RfVGJYQlEwdG1JVE5VdFg=
  RAZORPAY_KEY_SECRET: bmJ4aFZqSmlEeE9iQzRpYkdiWnIxOE9j
  RESEND_API_KEY: cmVfN0NlOFFmNDFfMjViSm9QeEY4cURYb3ZpQUdMSHBnWXph
